baseURL = "https://petrovski.co"
title = "VP"
copyright = "©2020, Vladimir Petrovski"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-163946879-1"
DisqusShortname = "petrovski-co"
theme = "hugo-theme-chunky-poster"
summaryLength = 60

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[params]
  author = "Vladimir Petrovski"
  description = "Exploring mobile technologies."
  homepageImage = "/images/homepage-image.png"
  greeting = "Glad to see you around!"
  hero = "I'm Vladimir and this is my space to write some thoughts & findings on mobile technologies, and er... life."
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["custom.css"]
  customJS = []

  [params.social]
    rss = true
    email = "vladimir.petrovski2@gmail.com"
    github = "https://github.com/vladimirpetrovski"
    twitter = "https://twitter.com/petrovskivlad"
    linkedin = "https://linkedin.com/in/vladimirpetrovski"
    instagram = "https://instagram.com/vladimir.petrovski"

  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
